/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

import java.awt.Color;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import searcher.Noticia;
import searcher.Searcher;

/**
 *
 * @author joseadiazg
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfazframe
     */
    public Interfaz() 
    {
        initComponents();
        setVisible(true);
    }
    
    public Interfaz(String cabecera, String cuerpo) 
    {
        initComponents();
        setVisible(true);
        salida.setText(cabecera+"\n"+cuerpo);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        texto = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        bool1 = new javax.swing.JTextField();
        bool2 = new javax.swing.JTextField();
        comboBox1 = new javax.swing.JComboBox();
        comboBox2 = new javax.swing.JComboBox();
        buscar2 = new javax.swing.JButton();
        checkAND = new javax.swing.JRadioButton();
        checkOR = new javax.swing.JRadioButton();
        rango1 = new javax.swing.JTextField();
        rango2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonRango = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboBoxOrden = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto.addActionListener(this::textoActionPerformed);

        buscar.setText("Buscar");
        buscar.addActionListener((java.awt.event.ActionEvent evt) -> {
            try {
                buscarActionPerformed(evt);
            } catch (IOException | ParseException | org.apache.lucene.queryparser.classic.ParseException ex) {
                Logger.getLogger(interfazframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        salida.setColumns(20);
        salida.setRows(5);
        salida.setText("Resultados...");
        jScrollPane2.setViewportView(salida);

        bool1.addActionListener(this::bool1ActionPerformed);

        bool2.addActionListener(this::bool2ActionPerformed);

        comboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plot", "Title" }));
        comboBox1.addActionListener(this::comboBox1ActionPerformed);

        comboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plot", "Title"}));

        buscar2.setText("Busqueda Booleana");
        buscar2.addActionListener(this::buscar2ActionPerformed);

        checkAND.setText("AND");
        checkAND.addActionListener(this::checkANDActionPerformed);

        checkOR.setText("OR");

        rango1.addActionListener(this::rango1ActionPerformed);

        rango2.addActionListener(this::rango2ActionPerformed);

        jLabel1.setText("Búsqueda Por Rango de años");

        jLabel2.setText("Búsquedas Avanzadas");

        botonRango.setText("Busqueda Rango");
        botonRango.addActionListener(this::botonRangoActionPerformed);

        jLabel4.setText("Consultas Simples");

        jLabel5.setText("Consultas Booleanas");

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/joseadiazg/Desktop/LuceneIndexer-master/logo.png")); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon("/Users/joseadiazg/Desktop/LuceneIndexer-master/salir.png")); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);

        comboBoxOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OrdenacionScore", "OrdenacionTitulo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(rango2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                            .addComponent(rango1))
                                        .addGap(58, 58, 58))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addComponent(checkAND)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(checkOR))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(comboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bool2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bool1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(6, 6, 6)))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buscar2)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonRango)
                                .addGap(63, 63, 63))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bool1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bool2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkAND)
                            .addComponent(checkOR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rango1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rango2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRango)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) throws IOException, ParseException, org.apache.lucene.queryparser.classic.ParseException {                                       
        
        String textoBuscar = texto.getText();
        Searcher buscador = new Searcher();
        ArrayList<Noticia> peliculas = new ArrayList();
        peliculas=buscador.busquedaTextoSinopsis(textoBuscar,comboBoxOrden.getSelectedItem().toString());
        
        salida.setBackground(Color.green);
        String textosalida = "Resultados:";
        String informacion=("Numero de resultados: " + peliculas.size());                   
        for(int i=0; i<peliculas.size(); i++)
        {      
            textosalida=textosalida.concat("Titulo: " + peliculas.get(i).getTitle()+
            "\n Actors:"+peliculas.get(i).getActors()+
            "\n Awards:"+peliculas.get(i).getAwards()+
            "\n Country:"+peliculas.get(i).getCountry()+"\n\n\n");
        }
         salida.setText(informacion+"\n\n"+textosalida);
        
    }                                     

    private void bool1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void buscar2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        ArrayList <String> campo = new ArrayList();
        ArrayList <String> cadena = new ArrayList();
        Searcher buscador = new Searcher();
        if (bool1.getText().equalsIgnoreCase(""))
        {
            salida.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "No se ha realizado ninguna consulta");
            
        }
        else 
        {
            campo.add(comboBox1.getSelectedItem().toString());
            cadena.add(bool1.getText());
            
            if(bool2.getText().equalsIgnoreCase(""))
            {
                salida.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Consulta booleana incorrecta");
                
            }
            else
            {
                campo.add(comboBox2.getSelectedItem().toString());
                cadena.add(bool2.getText());
                if(checkAND.isSelected()&&checkOR.isSelected())
                {
                    salida.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "No se puede realizar la consulta, selecciones solo 1 elemento booleano.");
                }
                
                else if(!checkAND.isSelected()&&!checkOR.isSelected())
                {
                    salida.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "No se puede realizar la consulta, selecciona AND o OR.");
                }
                else
                {
                    try {
                        ArrayList<Peliculas> peliculas = new ArrayList();
                        peliculas=buscador.consultaBooleana(campo, cadena, checkOR.isSelected(), checkAND.isSelected());
                        
                        salida.setBackground(Color.green);
                        String textosalida = "Resultados:";
                        String informacion=("Numero de resultados: " + peliculas.size());                   
                        for(int i=0; i<peliculas.size(); i++)
                        {                     
                           textosalida=textosalida.concat("Titulo: " + peliculas.get(i).getTitle()+
                                    "\n Actors:"+peliculas.get(i).getActors()+
                                    "\n Awards:"+peliculas.get(i).getAwards()+
                                    "\n Country:"+peliculas.get(i).getCountry()+"\n\n\n");
                        }
                        salida.setText(informacion+"\n\n"+textosalida);
                        
                        
                    } catch (IOException ex) {
                        Logger.getLogger(interfazframe.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (org.apache.lucene.queryparser.classic.ParseException ex) {
                        Logger.getLogger(interfazframe.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }  
                
            }
        }
    }                                       

    private void bool2ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void checkANDActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void comboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void rango1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void rango2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void botonRangoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        // TODO add your handling code here:
        Integer rangoA;
        Integer rangoB;
        String rangeA;
        String rangeB;
        Searcher buscador = new Searcher();
        
        if (rango1.getText().equals(""))
        {
            salida.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debes introducir un campo de rango incial.");
            
        }
        else 
        {
            rangeA=rango1.getText();
            rangoA=Integer.parseInt(rangeA);
            
            if(rango2.getText().equals(""))
            {
                salida.setBackground(Color.red);
                 JOptionPane.showMessageDialog(null, "Debes introducir un campo de rango final.");
                
            }
            else
            {
                rangeB=rango2.getText();
                rangoB=Integer.parseInt(rangeB);
                
                   
             
                try {
                     ArrayList<Peliculas> peliculas = new ArrayList();
                     peliculas=buscador.consultaRango(rangoA, rangoB,comboBoxOrden.getSelectedItem().toString());
                     salida.setBackground(Color.green);
                     String textosalida = "Resultados:";
                     String informacion=("Numero de resultados: " + peliculas.size());                   
                     for(int i=0; i<peliculas.size(); i++)
                     {                     
                        textosalida=textosalida.concat("Titulo: " + peliculas.get(i).getTitle()+
                                 "\n Actors:"+peliculas.get(i).getActors()+
                                 "\n Awards:"+peliculas.get(i).getAwards()+
                                 "\n Country:"+peliculas.get(i).getCountry()+"\n\n\n");
                     }
                     salida.setText(informacion+"\n\n"+textosalida);
                    
                } catch (IOException ex) {
                    Logger.getLogger(interfazframe.class.getName()).log(Level.SEVERE, null, ex);
                }
                    
            }
        }
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.exit(0);
    }                                        
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        interfazframe miInterfaz = new interfazframe();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new interfazframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField bool1;
    private javax.swing.JTextField bool2;
    private javax.swing.JButton botonRango;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscar2;
    private javax.swing.JRadioButton checkAND;
    private javax.swing.JRadioButton checkOR;
    private javax.swing.JComboBox comboBox1;
    private javax.swing.JComboBox comboBox2;
    private javax.swing.JComboBox comboBoxOrden;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField rango1;
    private javax.swing.JTextField rango2;
    private javax.swing.JTextArea salida;
    private javax.swing.JTextField texto;
    // End of variables declaration                   
}
